### ISSUE TITLE
Detailed documentation of installation

### ISSUE THREAD

**Issue by kartx22** [ulianovroman/NeuralChatBot#1]
Hi this repo was great can you make a clear documentation on how to use it?

**Comment by ulianovroman** [comment]
Hi there. Thanks for your interest! Unfortunatelly that project is not
ready yet. Now I'm trying to implement the right architecture​ of neural
network and here I had some problems. I hope that I'll finish it soon and
then a I'll make a documentation, of course!

**Comment by kartx22** [comment]
ok tanks for your quick response hope you finish this project sooner.
